name: Run Playwright + Cucumber Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step 1: Run Cucumber tests and generate JSON
      - name: Run Cucumber tests (JSON output)
        run: npm run test:cucumber

      # Step 2: Generate HTML report from JSON
      - name: Generate HTML report
        run: npm run test:cucumber:html

      # Step 3: Upload HTML report folder
      - name: Upload Cucumber HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: cucumber-report/html
